options:
  logging: CLOUD_LOGGING_ONLY   # 빌드 로그는 Cloud Logging에서만(문서 권장)
                                # → 콘솔 경고 사라지고 로그 한 곳으로 모임

substitutions:
  _REGION: asia-northeast3
  _SERVICE: quali-journal

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quali-journal:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quali-journal:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=gcr.io/$PROJECT_ID/quali-journal:$SHORT_SHA
      - --region=$_REGION
      - --platform=managed
      - --port=8080
      - --set-env-vars=APP_ENV=prod,QUALI_DB_MODE=prod,PYTHONIOENCODING=UTF-8
      - --set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest
