apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quali-admin-domap
  namespace: quali-journal-prod     # 프로젝트 ID 그대로!
spec:
  template:
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/quali-journal-prod/quali/qualijournal-admin:stable
        env:
        - name: PYTHONUTF8
          value: "1"
        - name: PYTHONIOENCODING
          value: "utf-8"
        ports:
        - name: http1
          containerPort: 8080
  traffic:
  - latestRevision: true
    percent: 100
