name: WIF Auth Check

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  auth-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/gha-actions"
          service_account: "gha-deploy-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          token_format: "access_token"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify access token & minimal permission
        shell: bash
        run: |
          set -euo pipefail
          echo "== gcloud auth list =="
          gcloud auth list
          echo "== token length =="
          gcloud auth print-access-token | wc -c
          echo "== list run services (optional) =="
          gcloud run services list --region asia-northeast3 || true
