name: WIF Auth Check
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  auth-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth via WIF
        uses: google-github-actions/auth@v2
        with:
          # ⚠️ 시크릿 대신 '정확한 경로'를 직접 넣는다 (테스트용)
          workload_identity_provider: "projects/656593003029/locations/global/workloadIdentityPools/github-pool/providers/gha-actions"
          service_account: "gha-deploy-sa@quali-journal-prod.iam.gserviceaccount.com"
          project_id: "quali-journal-prod"
          token_format: "access_token"


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify
        run: |
          echo "== gcloud auth list =="
          gcloud auth list
          echo "== token length =="
          gcloud auth print-access-token | wc -c

